# Generated by Django 3.2.9 on 2021-11-29 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='prize_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bonus.prize'),
        ),
    ]
