# Generated by Django 3.2.9 on 2021-11-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0003_auto_20211129_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prize',
            old_name='amount',
            new_name='prize_amount',
        ),
        migrations.RenameField(
            model_name='prize',
            old_name='cname',
            new_name='prize_cname',
        ),
        migrations.RenameField(
            model_name='prize',
            old_name='pid',
            new_name='prize_id',
        ),
    ]
