# Generated by Django 3.2.9 on 2021-12-06 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0004_auto_20211129_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prize',
            old_name='prize_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='prize',
            old_name='prize_cname',
            new_name='cname',
        ),
        migrations.RenameField(
            model_name='prize',
            old_name='prize_id',
            new_name='pid',
        ),
    ]
