# Generated by Django 3.2.9 on 2021-12-06 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0005_auto_20211206_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winner',
            old_name='prize_id',
            new_name='pid',
        ),
    ]
