# Generated by Django 3.2.9 on 2021-12-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0007_rename_pid_winner_prize_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winner',
            old_name='prize_id',
            new_name='pid',
        ),
    ]
