# Generated by Django 3.2.9 on 2021-12-06 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0008_rename_prize_id_winner_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonus.prize'),
        ),
    ]
