# Generated by Django 3.2.9 on 2021-12-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0009_alter_winner_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winner',
            old_name='pid',
            new_name='prize_id',
        ),
    ]
